In [ ]:
import numpy as np

def input_matrix(name):
    print(f"\nEnter dimensions for Matrix {name} (rows and columns, space-separated):")
    while True:
        dims = input(f"e.g. '2 2' for Matrix {name}: ").split()
        if len(dims) == 2:
            try:
                rows, cols = int(dims[0]), int(dims[1])
                break
            except ValueError:
                print("Please enter two whole numbers, like '2 2'. Try again:")
        else:
            print("Please enter exactly two numbers separated by a space, like '2 2'. Try again:")

    print(f"Enter the elements of Matrix {name} row by row (space-separated):")
    matrix = []
    for i in range(rows):
        while True:
            row = input(f"Row {i+1}: ").split()
            if len(row) == cols:
                try:
                    matrix.append(list(map(float, row)))
                    break
                except ValueError:
                    print(f"Please enter {cols} valid number(s), separated by space. Try again:")
            else:
                print(f"Please enter exactly {cols} number(s) for this row, separated by space. Try again:")

    return np.array(matrix)

def display_matrix(matrix, name="Result"):
    print(f"\n{name}:")
    print(matrix)

In [ ]:
def add_matrices(A, B):
    if A.shape != B.shape:
        return "Error: Matrices must have the same dimensions for addition."
    return A + B

def subtract_matrices(A, B):
    if A.shape != B.shape:
        return "Error: Matrices must have the same dimensions for subtraction."
    return A - B

def multiply_matrices(A, B):
    if A.shape[1] != B.shape[0]:
        return "Error: Number of columns in Matrix A must equal number of rows in Matrix B."
    return np.dot(A, B)

def transpose_matrix(A):
    return A.T

def determinant_matrix(A):
    if A.shape[0] != A.shape[1]:
        return "Error: Determinant can only be calculated for square matrices."
    return np.linalg.det(A)

In [ ]:
def matrix_operations_tool():
    print("="*50)
    print("       MATRIX OPERATIONS TOOL")
    print("="*50)

    while True:
        print("\nChoose an operation:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Transpose")
        print("5. Determinant")
        print("6. Exit")

        choice = input("\nEnter your choice (1-6): ")

        if choice == '6':
            print("\nExiting Matrix Operations Tool. Goodbye!")
            break

        if choice in ['1', '2', '3']:
            A = input_matrix("A")
            B = input_matrix("B")
            display_matrix(A, "Matrix A")
            display_matrix(B, "Matrix B")

            if choice == '1':
                result = add_matrices(A, B)
                display_matrix(result, "Addition Result (A + B)")
            elif choice == '2':
                result = subtract_matrices(A, B)
                display_matrix(result, "Subtraction Result (A - B)")
            elif choice == '3':
                result = multiply_matrices(A, B)
                display_matrix(result, "Multiplication Result (A x B)")

        elif choice == '4':
            A = input_matrix("A")
            display_matrix(A, "Original Matrix A")
            result = transpose_matrix(A)
            display_matrix(result, "Transpose of A")

        elif choice == '5':
            A = input_matrix("A")
            display_matrix(A, "Matrix A")
            result = determinant_matrix(A)
            print(f"\nDeterminant of A: {result}")

        else:
            print("\nInvalid choice! Please enter a number between 1 and 6.")

# Run the tool
matrix_operations_tool()

       MATRIX OPERATIONS TOOL

Choose an operation:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit

Enter your choice (1-6): 2 2

Invalid choice! Please enter a number between 1 and 6.

Choose an operation:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit

Enter your choice (1-6): 2

Enter dimensions for Matrix A (rows and columns, space-separated):
e.g. '2 2' for Matrix A: 2 2
Enter the elements of Matrix A row by row (space-separated):
Row 1: 1 2
Row 2: 3 4

Enter dimensions for Matrix B (rows and columns, space-separated):
e.g. '2 2' for Matrix B: 2 2
Enter the elements of Matrix B row by row (space-separated):
Row 1: 5 6
Row 2: 7 8

Matrix A:
[[1. 2.]
 [3. 4.]]

Matrix B:
[[5. 6.]
 [7. 8.]]

Subtraction Result (A - B):
[[-4. -4.]
 [-4. -4.]]

Choose an operation:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit
